/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.operation.Operation;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Operation op = new Operation(args);
        for(String a: args) {
            switch(a) {
                case "--ni" -> op.createFile();
                case "--md" -> op.createDirectory();
                case "--dd" -> op.deleteDirectory();
                case "--df" -> op.deleteFile();
                case "--ls" -> op.list();
                case "--cpf" -> op.copyFiles();
                case "--cpd" -> op.copyDirs();
                case "--mvf" -> op.moveFile();
                case "--mvd" -> op.moveDirs();
                case "--le" -> op.listEntries();
            }
        }
        System.out.println("Use --h to se the commands");
    }
}
