/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.operation.Operation;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Operation op = new Operation(args);
        for(String a: args) {
            switch(a) {
                case "--ni" -> op.createFile();
                case "--md" -> op.createDirectory();
                case "--le" -> op.listEntries();
            }
        }
    }
}
